
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar  7 2024 14:54:18 +07 (Mar  7 2024 07:54:18 UTC)

// Verification Directory fv/boundFlasher 

module boundFlasher(clk, flick, rst, lamps);
  input clk, flick, rst;
  output [15:0] lamps;
  wire clk, flick, rst;
  wire [15:0] lamps;
  wire [31:0] counter;
  wire [3:0] state;
  wire inc_add_39_26_n_283, inc_add_39_26_n_286, inc_add_39_26_n_289,
       inc_add_39_26_n_293, inc_add_39_26_n_295, inc_add_39_26_n_299,
       inc_add_39_26_n_301, inc_add_39_26_n_303;
  wire inc_add_39_26_n_305, inc_add_39_26_n_307, inc_add_39_26_n_309,
       inc_add_39_26_n_311, inc_add_39_26_n_313, inc_add_39_26_n_315,
       inc_add_39_26_n_317, inc_add_39_26_n_318;
  wire inc_add_39_26_n_323, inc_add_39_26_n_325, inc_add_39_26_n_326,
       inc_add_39_26_n_328, inc_add_39_26_n_329, inc_add_39_26_n_333,
       inc_add_39_26_n_334, inc_add_39_26_n_339;
  wire inc_add_39_26_n_340, inc_add_39_26_n_341, inc_add_39_26_n_345,
       inc_add_39_26_n_347, inc_add_39_26_n_353, inc_add_39_26_n_358,
       inc_add_39_26_n_363, inc_add_39_26_n_368;
  wire inc_add_39_26_n_373, n_0, n_2, n_3, n_10, n_11, n_12, n_13;
  wire n_19, n_21, n_27, n_28, n_33, n_34, n_35, n_36;
  wire n_37, n_41, n_45, n_50, n_52, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_64, n_66, n_68, n_71;
  wire n_72, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_84, n_89, n_101, n_102, n_103, n_104;
  wire n_107, n_108, n_109, n_110, n_112, n_114, n_116, n_117;
  wire n_123, n_127, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_139, n_144, n_149, n_152, n_166, n_167, n_171;
  wire n_172, n_173, n_176, n_180, n_182, n_184, n_185, n_188;
  wire n_189, n_190, n_191, n_193, n_197, n_200, n_201, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_210, n_211, n_212;
  wire n_213, n_215, n_216, n_218, n_219, n_220, n_221, n_223;
  wire n_225, n_226, n_229, n_230, n_231, n_232, n_243, n_246;
  wire n_249, n_251, n_257, n_259, n_263, n_266, n_268, n_269;
  wire n_270, n_271, n_272, n_273, n_279, n_280, n_281, n_283;
  wire n_284, n_285, n_287, n_288, n_289, n_291, n_292, n_293;
  wire n_295, n_296, n_297, n_299, n_300, n_301, n_303, n_305;
  wire n_315, n_358, n_359, n_372, n_392, n_393, n_417, n_425;
  wire n_443, n_448, n_450, n_451, n_456, n_492, n_498, n_499;
  wire n_503, n_504, n_506, n_508, n_512, n_513, n_514, n_516;
  wire n_518, n_520, n_521, n_524, n_527, n_532, n_535, n_538;
  wire n_565, n_579, n_595, n_598, n_599, n_600, n_601, n_602;
  wire n_613, n_621, n_629, n_635, n_646, n_647, n_654, n_696;
  wire n_697, n_698, n_699, n_700, n_704, n_705, n_706, n_709;
  wire n_710, n_721, n_734, n_735, n_737, n_738, n_741, n_746;
  wire n_747, n_750, n_751, n_755, n_758, n_760, n_761, n_766;
  wire n_767, n_769, n_770, n_804, n_805, n_806, n_807, n_808;
  wire n_809, n_810, n_813, n_814, n_815, n_816, n_818, n_819;
  wire n_820, n_821, n_823, n_824, n_825, n_827, n_831, n_832;
  wire n_833, n_834, n_836, n_837, n_838, n_858, n_859, n_860;
  wire n_868, n_870, n_871, n_872, n_873, n_874, n_875, n_876;
  wire n_877, n_881, n_887, n_888, n_889, n_890, n_891, n_892;
  wire n_894, n_895, n_896, n_902, n_903, n_904, n_905, n_906;
  wire n_907, n_909, n_913, n_914, n_915, n_916, n_917, n_919;
  wire n_920, n_923, n_924, n_925, n_926, n_928, n_929, n_930;
  wire n_950, n_951, n_952, n_953, n_954, n_1070, n_1071, n_1072;
  wire n_1074, n_1075, n_1078, n_1079, n_1080, n_1082, n_1083, n_1084;
  wire n_1086, n_1087, n_1088, n_1090, n_1091, n_1092, n_1094, n_1095;
  wire n_1096, n_1098, n_1099, n_1100, n_1102, n_1103, n_1104, n_1106;
  wire n_1107, n_1108, n_1110, n_1111, n_1113, n_1114, n_1115, n_1120;
  wire n_1121, n_1122, n_1123, n_1124, n_1125, n_1126, n_1127, n_1128;
  wire n_1129, n_1130, n_1131, n_1134, n_1135, n_1136, n_1137, n_1142;
  wire n_1143, n_1144, n_1145, n_1206, n_1207;
  SDFFQX1 \counter_reg[0] (.CK (clk), .D (n_838), .SI (n_646), .SE
       (counter[0]), .Q (counter[0]));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_1143), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_951), .Q (counter[2]));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_954), .Q (counter[3]));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_579), .Q (counter[4]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_1075), .Q (counter[5]));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_1107), .Q (counter[6]));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_251), .Q (counter[7]));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_926), .Q (counter[8]));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_249), .Q (counter[9]));
  DFFHQX1 \counter_reg[10] (.CK (clk), .D (n_1087), .Q (counter[10]));
  DFFHQX1 \counter_reg[11] (.CK (clk), .D (n_1079), .Q (counter[11]));
  DFFHQX1 \counter_reg[12] (.CK (clk), .D (n_246), .Q (counter[12]));
  DFFHQX1 \counter_reg[13] (.CK (clk), .D (n_1083), .Q (counter[13]));
  DFFHQX1 \counter_reg[14] (.CK (clk), .D (n_1099), .Q (counter[14]));
  DFFHQX1 \counter_reg[15] (.CK (clk), .D (n_243), .Q (counter[15]));
  DFFHQX1 \counter_reg[16] (.CK (clk), .D (n_257), .Q (counter[16]));
  DFFHQX1 \counter_reg[17] (.CK (clk), .D (n_272), .Q (counter[17]));
  DFFHQX1 \counter_reg[18] (.CK (clk), .D (n_270), .Q (counter[18]));
  DFFHQX1 \counter_reg[19] (.CK (clk), .D (n_271), .Q (counter[19]));
  DFFHQX1 \counter_reg[20] (.CK (clk), .D (n_269), .Q (counter[20]));
  DFFHQX1 \counter_reg[21] (.CK (clk), .D (n_268), .Q (counter[21]));
  DFFHQX1 \counter_reg[22] (.CK (clk), .D (n_1103), .Q (counter[22]));
  DFFHQX1 \counter_reg[23] (.CK (clk), .D (n_266), .Q (counter[23]));
  DFFHQX1 \counter_reg[24] (.CK (clk), .D (n_1111), .Q (counter[24]));
  DFFHQX1 \counter_reg[25] (.CK (clk), .D (n_1095), .Q (counter[25]));
  DFFHQX1 \counter_reg[26] (.CK (clk), .D (n_263), .Q (counter[26]));
  DFFHQX1 \counter_reg[27] (.CK (clk), .D (n_1115), .Q (counter[27]));
  DFFHQX1 \counter_reg[28] (.CK (clk), .D (n_1091), .Q (counter[28]));
  DFFHQX1 \counter_reg[29] (.CK (clk), .D (n_1071), .Q (counter[29]));
  DFFHQX1 \counter_reg[30] (.CK (clk), .D (n_259), .Q (counter[30]));
  DFFHQX1 \counter_reg[31] (.CK (clk), .D (n_273), .Q (counter[31]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_930), .Q (state[1]));
  DFFHQX1 \state_reg[2] (.CK (clk), .D (n_602), .Q (state[2]));
  DFFHQX4 \temp_reg[0] (.CK (clk), .D (n_1207), .Q (lamps[0]));
  DFFHQX4 \temp_reg[1] (.CK (clk), .D (n_230), .Q (lamps[1]));
  DFFHQX4 \temp_reg[2] (.CK (clk), .D (n_229), .Q (lamps[2]));
  DFFHQX4 \temp_reg[3] (.CK (clk), .D (n_232), .Q (lamps[3]));
  DFFHQX4 \temp_reg[4] (.CK (clk), .D (n_220), .Q (lamps[4]));
  DFFHQX4 \temp_reg[5] (.CK (clk), .D (n_924), .Q (lamps[5]));
  DFFHQX4 \temp_reg[10] (.CK (clk), .D (n_218), .Q (lamps[10]));
  DFFHQX4 \temp_reg[11] (.CK (clk), .D (n_223), .Q (lamps[11]));
  DFFHQX4 \temp_reg[12] (.CK (clk), .D (n_1137), .Q (lamps[12]));
  DFFHQX2 \temp_reg[13] (.CK (clk), .D (n_221), .Q (lamps[13]));
  DFFHQX4 \temp_reg[14] (.CK (clk), .D (n_231), .Q (lamps[14]));
  DFFHQX2 \temp_reg[15] (.CK (clk), .D (n_923), .Q (lamps[15]));
  OAI21X4 g8569__6260(.A0 (n_1124), .A1 (n_710), .B0 (n_117), .Y
       (n_273));
  OAI21X4 g8570__4319(.A0 (n_13), .A1 (n_710), .B0 (n_135), .Y (n_272));
  OAI21X4 g8571__8428(.A0 (n_1122), .A1 (n_710), .B0 (n_133), .Y
       (n_271));
  OAI21X4 g8572__5526(.A0 (n_21), .A1 (n_710), .B0 (n_134), .Y (n_270));
  OAI21X4 g8573__6783(.A0 (n_33), .A1 (n_710), .B0 (n_131), .Y (n_269));
  OAI21X4 g8574__3680(.A0 (n_34), .A1 (n_710), .B0 (n_130), .Y (n_268));
  OAI21X4 g8576__2802(.A0 (n_1123), .A1 (n_710), .B0 (n_127), .Y
       (n_266));
  OAI21X4 g8579__8246(.A0 (n_35), .A1 (n_710), .B0 (n_123), .Y (n_263));
  OAI21X4 g8583__5115(.A0 (n_19), .A1 (n_710), .B0 (n_110), .Y (n_259));
  OAI21X4 g8585__4733(.A0 (n_12), .A1 (n_710), .B0 (n_136), .Y (n_257));
  OAI21X4 g8591__1666(.A0 (n_1120), .A1 (n_710), .B0 (n_108), .Y
       (n_251));
  OAI21X4 g8593__6417(.A0 (n_41), .A1 (n_710), .B0 (n_109), .Y (n_249));
  OAI21X4 g8596__5107(.A0 (n_45), .A1 (n_710), .B0 (n_107), .Y (n_246));
  OAI21X4 g8599__8428(.A0 (n_1121), .A1 (n_710), .B0 (n_104), .Y
       (n_243));
  NAND3X4 g8626__7098(.A (n_210), .B (n_58), .C (n_184), .Y (n_232));
  NAND3X4 g8627__6131(.A (n_200), .B (n_61), .C (n_189), .Y (n_231));
  NAND3X4 g8628__1881(.A (n_213), .B (n_59), .C (n_173), .Y (n_230));
  NAND3X4 g8629__5115(.A (n_212), .B (n_57), .C (n_190), .Y (n_229));
  NAND2X4 g8632__6161(.A (n_207), .B (n_905), .Y (n_226));
  NAND2X4 g8633__9315(.A (n_205), .B (n_751), .Y (n_225));
  NAND3X4 g8635__9945(.A (n_211), .B (n_55), .C (n_166), .Y (n_223));
  NAND2X4 g8637__2346(.A (n_201), .B (n_191), .Y (n_221));
  NAND2X4 g8638__1666(.A (n_215), .B (n_197), .Y (n_220));
  NAND2X4 g8639__7410(.A (n_204), .B (n_193), .Y (n_219));
  NAND3X4 g8640__6417(.A (n_203), .B (n_60), .C (n_171), .Y (n_218));
  NAND2X4 g8642__2398(.A (n_206), .B (n_747), .Y (n_216));
  AOI21X4 g8643__5107(.A0 (lamps[5]), .A1 (n_860), .B0 (n_3), .Y
       (n_215));
  AOI21X4 g8645__4319(.A0 (lamps[2]), .A1 (n_860), .B0 (n_824), .Y
       (n_213));
  AOI21X4 g8646__8428(.A0 (lamps[3]), .A1 (n_860), .B0 (n_492), .Y
       (n_212));
  AOI21X4 g8647__5526(.A0 (lamps[12]), .A1 (n_860), .B0 (n_492), .Y
       (n_211));
  AOI21X4 g8648__6783(.A0 (lamps[4]), .A1 (n_860), .B0 (n_492), .Y
       (n_210));
  AOI21X4 g8650__1617(.A0 (lamps[6]), .A1 (n_860), .B0 (n_824), .Y
       (n_208));
  AOI21X4 g8651__2802(.A0 (lamps[7]), .A1 (n_860), .B0 (n_3), .Y
       (n_207));
  AOI21X4 g8652__1705(.A0 (lamps[9]), .A1 (n_860), .B0 (n_3), .Y
       (n_206));
  AOI21X4 g8653__5122(.A0 (lamps[8]), .A1 (n_860), .B0 (n_3), .Y
       (n_205));
  AOI21X4 g8654__8246(.A0 (lamps[10]), .A1 (n_860), .B0 (n_3), .Y
       (n_204));
  AOI21X4 g8655__7098(.A0 (lamps[11]), .A1 (n_860), .B0 (n_824), .Y
       (n_203));
  AOI21X4 g8657__1881(.A0 (lamps[14]), .A1 (n_860), .B0 (n_3), .Y
       (n_201));
  AOI21X4 g8658__5115(.A0 (lamps[15]), .A1 (n_860), .B0 (n_492), .Y
       (n_200));
  NOR2X4 g8661__6161(.A (n_188), .B (n_913), .Y (n_197));
  NOR2X4 g8665__2346(.A (n_182), .B (n_172), .Y (n_193));
  NOR2X4 g8667__7410(.A (n_167), .B (n_185), .Y (n_191));
  NAND2X4 g8668__6417(.A (lamps[2]), .B (n_823), .Y (n_190));
  NAND2X4 g8669__5477(.A (lamps[14]), .B (n_823), .Y (n_189));
  NOR2X4 g8670__2398(.A (n_706), .B (n_874), .Y (n_188));
  NOR2X4 g8674__4319(.A (n_64), .B (n_874), .Y (n_185));
  NAND2X4 g8675__8428(.A (lamps[3]), .B (n_823), .Y (n_184));
  CLKAND2X3 g8677__6783(.A (lamps[8]), .B (n_914), .Y (n_182));
  NAND2X4 g8680__1617(.A (lamps[0]), .B (n_823), .Y (n_180));
  NAND2X4 g8691__1881(.A (lamps[1]), .B (n_823), .Y (n_173));
  NOR2X4 g8692__5115(.A (n_11), .B (n_874), .Y (n_172));
  NAND2X4 g8693__7482(.A (lamps[10]), .B (n_823), .Y (n_171));
  CLKAND2X6 g8697__9945(.A (lamps[12]), .B (n_914), .Y (n_167));
  NAND2X4 g8699__2883(.A (lamps[11]), .B (n_823), .Y (n_166));
  AOI21X1 g8712__5526(.A0 (n_50), .A1 (n_358), .B0 (n_813), .Y (n_152));
  NAND2BX1 g8717__1705(.AN (n_139), .B (n_72), .Y (n_149));
  NAND2X1 g8720__5122(.A (n_139), .B (n_72), .Y (n_144));
  AND4X1 g8732__9315(.A (n_27), .B (n_706), .C (n_74), .D (n_0), .Y
       (n_139));
  NAND2X2 g8734__2883(.A (counter[16]), .B (n_654), .Y (n_136));
  NAND2X2 g8735__2346(.A (counter[17]), .B (n_654), .Y (n_135));
  NAND2X2 g8736__1666(.A (counter[18]), .B (n_654), .Y (n_134));
  NAND2X2 g8737__7410(.A (counter[19]), .B (n_647), .Y (n_133));
  NAND2X2 g8738__6417(.A (counter[4]), .B (n_654), .Y (n_132));
  NAND2X2 g8739__5477(.A (counter[20]), .B (n_647), .Y (n_131));
  NAND2X2 g8740__2398(.A (counter[21]), .B (n_654), .Y (n_130));
  NAND2X2 g8743__4319(.A (counter[23]), .B (n_654), .Y (n_127));
  NAND2X2 g8747__3680(.A (counter[26]), .B (n_647), .Y (n_123));
  NAND2X2 g8753__7098(.A (counter[31]), .B (n_647), .Y (n_117));
  NOR2X1 g8757__1881(.A (lamps[5]), .B (n_705), .Y (n_114));
  NAND2X2 g8759__7482(.A (counter[2]), .B (n_654), .Y (n_112));
  NAND2X2 g8761__6161(.A (counter[30]), .B (n_647), .Y (n_110));
  NAND2X2 g8762__9315(.A (counter[9]), .B (n_654), .Y (n_109));
  NAND2X2 g8763__9945(.A (counter[7]), .B (n_647), .Y (n_108));
  NAND2X2 g8764__2883(.A (counter[12]), .B (n_654), .Y (n_107));
  NAND2X2 g8767__7410(.A (counter[15]), .B (n_654), .Y (n_104));
  NAND2X2 g8768__6417(.A (counter[3]), .B (n_654), .Y (n_103));
  NOR3X1 g8769__5477(.A (n_71), .B (n_2), .C (n_89), .Y (n_102));
  NOR4BBX1 g8770__2398(.AN (lamps[10]), .BN (n_809), .C (lamps[11]), .D
       (n_89), .Y (n_101));
  NOR2X1 g8773__6260(.A (n_27), .B (n_705), .Y (n_116));
  NOR3X1 g8784__1705(.A (counter[1]), .B (counter[2]), .C (n_68), .Y
       (n_84));
  OR4X1 g8788__7098(.A (n_11), .B (n_10), .C (n_741), .D (n_28), .Y
       (n_89));
  NOR3BX1 g8793__7482(.AN (counter[7]), .B (counter[8]), .C (n_66), .Y
       (n_82));
  NOR4X1 g8794__4733(.A (counter[9]), .B (counter[10]), .C
       (counter[11]), .D (counter[12]), .Y (n_81));
  NOR4X1 g8795__6161(.A (counter[13]), .B (counter[14]), .C
       (counter[15]), .D (counter[16]), .Y (n_80));
  OR4X1 g8796__9315(.A (counter[30]), .B (counter[29]), .C
       (counter[21]), .D (counter[31]), .Y (n_79));
  OR4X1 g8797__9945(.A (counter[19]), .B (counter[18]), .C
       (counter[0]), .D (counter[20]), .Y (n_78));
  OR4X1 g8798__2883(.A (counter[26]), .B (counter[17]), .C
       (counter[25]), .D (counter[28]), .Y (n_77));
  OR4X1 g8799__2346(.A (counter[23]), .B (counter[22]), .C
       (counter[24]), .D (counter[27]), .Y (n_76));
  AND4X1 g8800__1666(.A (n_28), .B (n_741), .C (n_11), .D (n_10), .Y
       (n_75));
  NOR4X1 g8801__7410(.A (lamps[0]), .B (lamps[1]), .C (lamps[2]), .D
       (lamps[3]), .Y (n_74));
  NAND2X1 g8803__5477(.A (lamps[11]), .B (lamps[10]), .Y (n_71));
  AND2X1 g8806__5107(.A (state[1]), .B (n_917), .Y (n_72));
  NAND2BX1 g8807__6260(.AN (counter[4]), .B (counter[3]), .Y (n_68));
  NAND2BX1 g8809__8428(.AN (counter[5]), .B (counter[6]), .Y (n_66));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_920), .Q (state[0]));
  NAND4BBXL g2__2802(.AN (n_64), .BN (n_565), .C (lamps[15]), .D
       (lamps[14]), .Y (n_2));
  NOR4BBX2 g8971__5122(.AN (n_75), .BN (n_809), .C (lamps[11]), .D
       (lamps[10]), .Y (n_0));
  INVX1 g8973(.A (lamps[5]), .Y (n_27));
  INVX1 g8977(.A (lamps[6]), .Y (n_28));
  INVX1 g8981(.A (lamps[9]), .Y (n_11));
  INVX1 g8983(.A (lamps[8]), .Y (n_10));
  INVX1 g8997(.A (n_279), .Y (n_36));
  INVX1 g9007(.A (n_284), .Y (n_41));
  INVX1 g9013(.A (n_287), .Y (n_45));
  INVX1 g9021(.A (n_291), .Y (n_12));
  INVX1 g9023(.A (n_292), .Y (n_13));
  INVX1 g9025(.A (n_293), .Y (n_21));
  INVX1 g9029(.A (n_295), .Y (n_33));
  INVX1 g9031(.A (n_296), .Y (n_34));
  INVX1 g9041(.A (n_301), .Y (n_35));
  INVX1 g9049(.A (n_305), .Y (n_19));
  NAND2X2 g9061__1881(.A (lamps[2]), .B (n_914), .Y (n_58));
  INVX1 g9075(.A (n_448), .Y (n_52));
  INVX1 g9077(.A (n_359), .Y (n_50));
  ADDHX1 inc_add_39_26_g522__1666(.A (counter[26]), .B
       (inc_add_39_26_n_293), .CO (inc_add_39_26_n_283), .S (n_301));
  ADDHX1 inc_add_39_26_g524__6417(.A (counter[22]), .B
       (inc_add_39_26_n_301), .CO (inc_add_39_26_n_286), .S (n_297));
  ADDHX1 inc_add_39_26_g526__2398(.A (counter[18]), .B
       (inc_add_39_26_n_305), .CO (inc_add_39_26_n_289), .S (n_293));
  ADDHX1 inc_add_39_26_g529__4319(.A (counter[25]), .B
       (inc_add_39_26_n_311), .CO (inc_add_39_26_n_293), .S (n_300));
  ADDHX1 inc_add_39_26_g530__8428(.A (counter[14]), .B
       (inc_add_39_26_n_313), .CO (inc_add_39_26_n_295), .S (n_289));
  ADDHX1 inc_add_39_26_g533__3680(.A (counter[30]), .B
       (inc_add_39_26_n_318), .CO (inc_add_39_26_n_299), .S (n_305));
  ADDHX1 inc_add_39_26_g534__1617(.A (counter[21]), .B
       (inc_add_39_26_n_317), .CO (inc_add_39_26_n_301), .S (n_296));
  ADDHX1 inc_add_39_26_g535__2802(.A (counter[10]), .B
       (inc_add_39_26_n_315), .CO (inc_add_39_26_n_303), .S (n_285));
  ADDHX1 inc_add_39_26_g536__1705(.A (counter[17]), .B
       (inc_add_39_26_n_325), .CO (inc_add_39_26_n_305), .S (n_292));
  ADDHX1 inc_add_39_26_g537__5122(.A (counter[6]), .B
       (inc_add_39_26_n_323), .CO (inc_add_39_26_n_307), .S (n_281));
  ADDHX1 inc_add_39_26_g538__8246(.A (counter[28]), .B
       (inc_add_39_26_n_326), .CO (inc_add_39_26_n_309), .S (n_303));
  ADDHX1 inc_add_39_26_g539__7098(.A (counter[24]), .B
       (inc_add_39_26_n_329), .CO (inc_add_39_26_n_311), .S (n_299));
  ADDHX1 inc_add_39_26_g540__6131(.A (counter[13]), .B
       (inc_add_39_26_n_328), .CO (inc_add_39_26_n_313), .S (n_288));
  ADDHX1 inc_add_39_26_g541__1881(.A (counter[9]), .B
       (inc_add_39_26_n_333), .CO (inc_add_39_26_n_315), .S (n_284));
  ADDHX1 inc_add_39_26_g542__5115(.A (counter[20]), .B
       (inc_add_39_26_n_334), .CO (inc_add_39_26_n_317), .S (n_295));
  AND3XL inc_add_39_26_g543__7482(.A (counter[28]), .B (counter[29]),
       .C (inc_add_39_26_n_326), .Y (inc_add_39_26_n_318));
  ADDHX1 inc_add_39_26_g544__4733(.A (counter[5]), .B
       (inc_add_39_26_n_339), .CO (inc_add_39_26_n_323), .S (n_280));
  ADDHX1 inc_add_39_26_g545__6161(.A (counter[16]), .B
       (inc_add_39_26_n_341), .CO (inc_add_39_26_n_325), .S (n_291));
  NOR4X1 inc_add_39_26_g546__9315(.A (inc_add_39_26_n_363), .B
       (inc_add_39_26_n_358), .C (n_1129), .D (inc_add_39_26_n_340), .Y
       (inc_add_39_26_n_326));
  ADDHX1 inc_add_39_26_g547__9945(.A (counter[12]), .B
       (inc_add_39_26_n_345), .CO (inc_add_39_26_n_328), .S (n_287));
  NOR2BX1 inc_add_39_26_g548__2883(.AN (inc_add_39_26_n_334), .B
       (inc_add_39_26_n_358), .Y (inc_add_39_26_n_329));
  ADDHX1 inc_add_39_26_g549__2346(.A (counter[8]), .B
       (inc_add_39_26_n_347), .CO (inc_add_39_26_n_333), .S (n_283));
  NOR2X2 inc_add_39_26_g550__1666(.A (n_1129), .B
       (inc_add_39_26_n_340), .Y (inc_add_39_26_n_334));
  ADDHX1 inc_add_39_26_g552__6417(.A (counter[4]), .B (n_1128), .CO
       (inc_add_39_26_n_339), .S (n_279));
  NAND2X1 inc_add_39_26_g554__5477(.A (inc_add_39_26_n_368), .B
       (inc_add_39_26_n_345), .Y (inc_add_39_26_n_340));
  AND2X2 inc_add_39_26_g556__5107(.A (inc_add_39_26_n_353), .B
       (inc_add_39_26_n_347), .Y (inc_add_39_26_n_345));
  NOR2BX1 inc_add_39_26_g557__6260(.AN (n_1128), .B
       (inc_add_39_26_n_373), .Y (inc_add_39_26_n_347));
  AND4X1 inc_add_39_26_g560__5526(.A (counter[8]), .B (counter[9]), .C
       (counter[10]), .D (counter[11]), .Y (inc_add_39_26_n_353));
  NAND4XL inc_add_39_26_g561__6783(.A (counter[20]), .B (counter[21]),
       .C (counter[22]), .D (counter[23]), .Y (inc_add_39_26_n_358));
  NAND4XL inc_add_39_26_g562__3680(.A (counter[24]), .B (counter[25]),
       .C (counter[26]), .D (counter[27]), .Y (inc_add_39_26_n_363));
  AND4X1 inc_add_39_26_g563__1617(.A (counter[12]), .B (counter[13]),
       .C (counter[14]), .D (counter[15]), .Y (inc_add_39_26_n_368));
  NAND4X1 inc_add_39_26_g564__2802(.A (counter[4]), .B (counter[5]), .C
       (counter[6]), .D (counter[7]), .Y (inc_add_39_26_n_373));
  INVX1 inc_add_39_26_g572(.A (inc_add_39_26_n_340), .Y
       (inc_add_39_26_n_341));
  DFFHQX1 \temp_reg[8] (.CK (clk), .D (n_216), .Q (lamps[8]));
  DFFHQX1 \temp_reg[7] (.CK (clk), .D (n_225), .Q (lamps[7]));
  DFFHQX1 \temp_reg[9] (.CK (clk), .D (n_219), .Q (lamps[9]));
  DFFHQX1 \temp_reg[6] (.CK (clk), .D (n_226), .Q (lamps[6]));
  OAI21X4 g8601__9110(.A0 (n_499), .A1 (n_915), .B0 (state[1]), .Y
       (n_315));
  AND2X1 g435(.A (n_917), .B (n_804), .Y (n_358));
  AND2X1 g442(.A (n_0), .B (n_114), .Y (n_359));
  NOR2X1 g443(.A (state[2]), .B (n_518), .Y (n_372));
  INVX1 g753(.A (n_392), .Y (n_393));
  ADDHX1 g740(.A (counter[0]), .B (counter[1]), .CO (n_425), .S
       (n_417));
  NOR2X1 g29(.A (n_805), .B (n_833), .Y (n_443));
  NAND2X1 g133(.A (n_0), .B (n_116), .Y (n_448));
  NOR2BX1 g129(.AN (n_450), .B (n_805), .Y (n_451));
  AND2X1 g132(.A (n_102), .B (n_116), .Y (n_450));
  NOR2BX1 g137(.AN (n_372), .B (n_535), .Y (n_456));
  CLKINVX6 g9148(.A (n_825), .Y (n_492));
  NOR2X6 g37(.A (n_508), .B (n_498), .Y (n_499));
  NOR2X1 g96(.A (n_805), .B (n_535), .Y (n_503));
  OR3X1 g95(.A (n_504), .B (n_896), .C (n_451), .Y (n_506));
  AO22X1 g98(.A0 (n_813), .A1 (n_833), .B0 (n_358), .B1 (n_359), .Y
       (n_504));
  BUFX2 g9151(.A (state[2]), .Y (n_508));
  NOR2X2 g1525(.A (n_512), .B (rst), .Y (n_513));
  AO21X1 g1532(.A0 (n_698), .A1 (n_456), .B0 (n_506), .Y (n_512));
  NAND2X4 g1531(.A (n_514), .B (flick), .Y (n_516));
  OR2X4 g1537(.A (n_503), .B (n_456), .Y (n_514));
  NOR2X2 g1522(.A (n_813), .B (rst), .Y (n_520));
  NAND2X1 g1535(.A (state[0]), .B (state[1]), .Y (n_518));
  OR3X1 g1534(.A (state[2]), .B (n_456), .C (n_506), .Y (n_524));
  OR3X1 g1533(.A (state[2]), .B (n_698), .C (n_506), .Y (n_527));
  NAND2BX2 g1524(.AN (n_512), .B (n_516), .Y (n_532));
  OAI31X2 g124(.A0 (n_805), .A1 (n_833), .A2 (n_450), .B0 (n_827), .Y
       (n_538));
  NOR2X2 g9154(.A (n_698), .B (n_52), .Y (n_535));
  OAI21X4 g27(.A0 (n_36), .A1 (n_710), .B0 (n_132), .Y (n_579));
  INVX1 g92(.A (state[2]), .Y (n_595));
  OAI22X2 g84(.A0 (n_600), .A1 (n_601), .B0 (n_595), .B1 (n_919), .Y
       (n_602));
  OAI21X2 g85(.A0 (n_527), .A1 (flick), .B0 (n_599), .Y (n_600));
  NAND2X2 g86(.A (n_598), .B (flick), .Y (n_599));
  AND2X1 g87(.A (n_595), .B (n_809), .Y (n_598));
  NAND2X4 g91(.A (n_520), .B (n_1130), .Y (n_601));
  NAND3X1 g9177(.A (lamps[11]), .B (state[0]), .C (n_833), .Y (n_613));
  NOR2X8 g9183(.A (n_393), .B (rst), .Y (n_621));
  INVX1 g73(.A (lamps[12]), .Y (n_565));
  BUFX2 g9191(.A (n_392), .Y (n_629));
  INVX1 g9193(.A (n_629), .Y (n_635));
  CLKINVX16 fopt9200(.A (n_621), .Y (n_647));
  CLKINVX12 fopt9201(.A (n_621), .Y (n_654));
  BUFX16 fopt9204(.A (n_647), .Y (n_646));
  NAND2X8 g9218(.A (n_696), .B (flick), .Y (n_697));
  OR4X2 g9219(.A (n_809), .B (n_805), .C (n_833), .D (n_450), .Y
       (n_696));
  NAND2BX1 g9222(.AN (n_698), .B (n_699), .Y (n_700));
  AND2X1 g9223(.A (n_101), .B (n_116), .Y (n_698));
  NOR2BX1 g67(.AN (n_372), .B (n_833), .Y (n_699));
  NAND3X1 g9224(.A (lamps[1]), .B (lamps[3]), .C (n_704), .Y (n_705));
  AND3XL g9225(.A (lamps[2]), .B (lamps[0]), .C (lamps[4]), .Y (n_704));
  CLKINVX20 g9227(.A (n_709), .Y (n_710));
  NAND2X8 g33(.A (n_738), .B (n_770), .Y (n_709));
  NAND2X2 g110(.A (counter[1]), .B (n_647), .Y (n_721));
  NOR2X8 g9246(.A (n_734), .B (rst), .Y (n_735));
  NOR2BX4 g9247(.AN (n_1135), .B (n_538), .Y (n_734));
  NAND2X8 g9248(.A (n_1145), .B (n_737), .Y (n_738));
  NOR2X8 g9207_dup(.A (n_734), .B (rst), .Y (n_737));
  INVX1 g9250(.A (lamps[7]), .Y (n_741));
  NOR2X4 g20(.A (n_870), .B (n_746), .Y (n_747));
  NOR2X4 g9253(.A (n_10), .B (n_874), .Y (n_746));
  NOR2X4 g19(.A (n_868), .B (n_750), .Y (n_751));
  NOR2BX4 g9256(.AN (lamps[7]), .B (n_874), .Y (n_750));
  CLKINVX16 fopt9262(.A (rst), .Y (n_758));
  CLKINVX6 fopt9264(.A (rst), .Y (n_761));
  NOR2X8 g9266(.A (n_766), .B (rst), .Y (n_767));
  AND2X2 g9267(.A (n_696), .B (n_700), .Y (n_766));
  NAND2X8 g9268(.A (n_697), .B (n_769), .Y (n_770));
  NOR2X8 g11_dup(.A (n_766), .B (rst), .Y (n_769));
  NAND2X6 g9270(.A (n_809), .B (flick), .Y (n_498));
  INVX1 g9280(.A (n_805), .Y (n_806));
  NAND2X2 g9281(.A (state[0]), .B (n_804), .Y (n_805));
  NOR2X1 g59(.A (state[1]), .B (n_595), .Y (n_804));
  NAND2X8 g9282(.A (n_809), .B (flick), .Y (n_810));
  AND2X2 g58(.A (n_807), .B (n_808), .Y (n_809));
  NOR2X1 g9283(.A (lamps[14]), .B (lamps[13]), .Y (n_807));
  NOR2X1 g9284(.A (lamps[12]), .B (lamps[15]), .Y (n_808));
  INVX3 g79(.A (n_815), .Y (n_816));
  NOR2X8 g80(.A (n_814), .B (rst), .Y (n_815));
  INVX1 g9287(.A (n_813), .Y (n_814));
  NOR2X1 g9288(.A (n_595), .B (n_518), .Y (n_813));
  NAND3X2 g75(.A (lamps[15]), .B (n_818), .C (n_820), .Y (n_821));
  NAND2X8 g9289(.A (n_635), .B (n_758), .Y (n_818));
  NOR2X8 g9291(.A (n_834), .B (rst), .Y (n_819));
  CLKAND2X12 g81(.A (n_818), .B (n_820), .Y (n_823));
  CLKINVX6 g78(.A (n_816), .Y (n_824));
  INVX2 g77(.A (n_815), .Y (n_825));
  NAND2X1 g23(.A (n_699), .B (n_535), .Y (n_827));
  AND2X2 g46(.A (n_831), .B (n_832), .Y (n_833));
  NOR4X1 g48(.A (n_79), .B (n_78), .C (n_76), .D (n_77), .Y (n_831));
  AND4X1 g47(.A (n_80), .B (n_81), .C (n_82), .D (n_84), .Y (n_832));
  NAND2X8 g32(.A (n_836), .B (n_837), .Y (n_838));
  NAND2X8 g36(.A (n_1145), .B (n_735), .Y (n_836));
  NAND2X8 g38(.A (n_697), .B (n_767), .Y (n_837));
  CLKAND2X12 g10(.A (n_858), .B (n_859), .Y (n_860));
  NOR2XL g11(.A (n_881), .B (n_834), .Y (n_858));
  CLKINVX16 fopt(.A (rst), .Y (n_859));
  AND2X1 g41(.A (n_888), .B (n_761), .Y (n_868));
  AND2X1 g42(.A (n_887), .B (n_755), .Y (n_870));
  CLKINVX12 g9306(.A (n_873), .Y (n_874));
  NOR2X8 g9307(.A (n_871), .B (n_872), .Y (n_873));
  NOR2X8 g9308(.A (n_834), .B (rst), .Y (n_871));
  NOR2X8 g9309(.A (n_629), .B (rst), .Y (n_872));
  NOR2X2 g9310(.A (n_565), .B (n_872), .Y (n_875));
  OR2X1 g55(.A (state[2]), .B (state[1]), .Y (n_876));
  NOR2X4 g54(.A (state[0]), .B (rst), .Y (n_877));
  OR2X1 g51(.A (state[0]), .B (n_876), .Y (n_392));
  NAND2X1 g52(.A (n_876), .B (n_917), .Y (n_881));
  AND2X1 g34(.A (lamps[7]), .B (n_909), .Y (n_887));
  AND2X1 g35(.A (lamps[6]), .B (n_909), .Y (n_888));
  NAND2X4 g103(.A (n_890), .B (n_891), .Y (n_892));
  NOR2BX1 g105(.AN (n_889), .B (n_72), .Y (n_890));
  OR2X1 g106(.A (n_917), .B (n_876), .Y (n_889));
  NAND2X6 g107(.A (n_806), .B (n_810), .Y (n_891));
  NAND3X1 g100(.A (n_894), .B (n_149), .C (n_152), .Y (n_895));
  OR2X1 g104(.A (n_889), .B (n_52), .Y (n_894));
  OAI211X1 g101(.A0 (n_889), .A1 (n_448), .B0 (n_392), .C0 (n_144), .Y
       (n_896));
  NOR2X4 g9321(.A (n_903), .B (n_904), .Y (n_905));
  AND2X1 g9322(.A (n_902), .B (n_755), .Y (n_903));
  AND2X1 g25(.A (lamps[5]), .B (n_909), .Y (n_902));
  NOR2X4 g9323(.A (n_28), .B (n_874), .Y (n_904));
  NAND2X2 g13(.A (n_820), .B (n_875), .Y (n_907));
  AND2X1 g9325(.A (state[0]), .B (n_833), .Y (n_909));
  AND3X4 g8(.A (lamps[3]), .B (n_909), .C (n_758), .Y (n_913));
  CLKAND2X12 g9(.A (n_909), .B (n_758), .Y (n_914));
  OAI22X2 g56(.A0 (n_915), .A1 (n_916), .B0 (n_917), .B1 (n_919), .Y
       (n_920));
  AOI21X4 g57(.A0 (n_514), .A1 (flick), .B0 (n_512), .Y (n_915));
  OAI21X2 g9328(.A0 (n_876), .A1 (flick), .B0 (n_877), .Y (n_916));
  INVX1 g9329(.A (state[0]), .Y (n_917));
  NAND2X4 g9330(.A (n_513), .B (n_516), .Y (n_919));
  NAND3X2 g9331(.A (n_816), .B (n_1134), .C (n_821), .Y (n_923));
  NAND3X4 g16(.A (n_56), .B (n_176), .C (n_208), .Y (n_924));
  OAI21X4 g9332(.A0 (n_37), .A1 (n_710), .B0 (n_925), .Y (n_926));
  NAND2X6 g21(.A (counter[8]), .B (n_646), .Y (n_925));
  OAI22X4 g62(.A0 (n_928), .A1 (n_929), .B0 (n_760), .B1 (n_315), .Y
       (n_930));
  NAND2X6 g64(.A (n_761), .B (n_892), .Y (n_928));
  NOR2X2 g63(.A (n_72), .B (n_532), .Y (n_929));
  OAI21X4 g9354(.A0 (n_950), .A1 (n_1113), .B0 (n_112), .Y (n_951));
  XNOR2X2 g3(.A (counter[2]), .B (n_425), .Y (n_950));
  OAI21X4 g9356(.A0 (n_953), .A1 (n_1113), .B0 (n_103), .Y (n_954));
  XNOR2X2 g9357(.A (counter[3]), .B (n_952), .Y (n_953));
  NAND2X6 g8688__9462(.A (lamps[5]), .B (n_823), .Y (n_176));
  CLKINVX8 g9464(.A (n_819), .Y (n_820));
  OAI21X4 g9475(.A0 (n_1125), .A1 (n_1113), .B0 (n_1070), .Y (n_1071));
  NAND2X2 g9477(.A (counter[29]), .B (n_647), .Y (n_1070));
  OAI21X4 g9478(.A0 (n_1072), .A1 (n_1113), .B0 (n_1074), .Y (n_1075));
  INVX1 g9479(.A (n_280), .Y (n_1072));
  NAND2X2 g9481(.A (counter[5]), .B (n_647), .Y (n_1074));
  OAI21X4 g9482(.A0 (n_1126), .A1 (n_1113), .B0 (n_1078), .Y (n_1079));
  NAND2X2 g9485(.A (counter[11]), .B (n_647), .Y (n_1078));
  OAI21X4 g9486(.A0 (n_1080), .A1 (n_1113), .B0 (n_1082), .Y (n_1083));
  INVX1 g9487(.A (n_288), .Y (n_1080));
  NAND2X2 g9489(.A (counter[13]), .B (n_654), .Y (n_1082));
  OAI21X4 g9490(.A0 (n_1084), .A1 (n_1113), .B0 (n_1086), .Y (n_1087));
  INVX1 g9491(.A (n_285), .Y (n_1084));
  NAND2X2 g9493(.A (counter[10]), .B (n_647), .Y (n_1086));
  OAI21X4 g9494(.A0 (n_1088), .A1 (n_1113), .B0 (n_1090), .Y (n_1091));
  INVX1 g9495(.A (n_303), .Y (n_1088));
  NAND2X2 g9497(.A (counter[28]), .B (n_647), .Y (n_1090));
  OAI21X4 g9498(.A0 (n_1092), .A1 (n_1113), .B0 (n_1094), .Y (n_1095));
  INVX1 g9499(.A (n_300), .Y (n_1092));
  NAND2X2 g9501(.A (counter[25]), .B (n_654), .Y (n_1094));
  OAI21X4 g9502(.A0 (n_1096), .A1 (n_1113), .B0 (n_1098), .Y (n_1099));
  INVX1 g9503(.A (n_289), .Y (n_1096));
  NAND2X2 g9505(.A (counter[14]), .B (n_654), .Y (n_1098));
  OAI21X4 g9506(.A0 (n_1100), .A1 (n_1113), .B0 (n_1102), .Y (n_1103));
  INVX1 g9507(.A (n_297), .Y (n_1100));
  NAND2X2 g9509(.A (counter[22]), .B (n_647), .Y (n_1102));
  OAI21X4 g9510(.A0 (n_1104), .A1 (n_1113), .B0 (n_1106), .Y (n_1107));
  INVX1 g9511(.A (n_281), .Y (n_1104));
  NAND2X2 g9513(.A (counter[6]), .B (n_647), .Y (n_1106));
  OAI21X4 g9514(.A0 (n_1108), .A1 (n_1113), .B0 (n_1110), .Y (n_1111));
  INVX1 g9515(.A (n_299), .Y (n_1108));
  NAND2X2 g9517(.A (counter[24]), .B (n_654), .Y (n_1110));
  OAI21X4 g9518(.A0 (n_1127), .A1 (n_1113), .B0 (n_1114), .Y (n_1115));
  CLKINVX20 g9520(.A (n_838), .Y (n_1113));
  NAND2X2 g9521(.A (counter[27]), .B (n_654), .Y (n_1114));
  XNOR2X2 g9538(.A (counter[29]), .B (inc_add_39_26_n_309), .Y
       (n_1125));
  XNOR2X2 g9539(.A (counter[11]), .B (inc_add_39_26_n_303), .Y
       (n_1126));
  XNOR2X2 g9540(.A (counter[27]), .B (inc_add_39_26_n_283), .Y
       (n_1127));
  AND3X1 g9541(.A (counter[2]), .B (counter[3]), .C (n_425), .Y
       (n_1128));
  NAND4XL g9542(.A (counter[16]), .B (counter[17]), .C (counter[18]),
       .D (counter[19]), .Y (n_1129));
  AOI2BB1X4 g9543(.A0N (n_524), .A1N (flick), .B0 (n_1131), .Y
       (n_1130));
  AOI2BB1X1 g9544(.A0N (n_518), .A1N (n_521), .B0 (state[2]), .Y
       (n_1131));
  NAND3BX2 g9547(.AN (rst), .B (lamps[14]), .C (n_909), .Y (n_1134));
  AOI32X2 g9548(.A0 (n_809), .A1 (n_443), .A2 (n_535), .B0 (n_834), .B1
       (n_895), .Y (n_1135));
  NAND3X4 g9549(.A (n_1136), .B (n_906), .C (n_907), .Y (n_1137));
  AOI21X4 g9550(.A0 (lamps[13]), .A1 (n_860), .B0 (n_3), .Y (n_1136));
  XNOR2X1 g9556(.A (counter[7]), .B (inc_add_39_26_n_307), .Y (n_1120));
  OR2X1 g9558(.A (n_613), .B (rst), .Y (n_906));
  INVX1 g9560(.A (lamps[4]), .Y (n_706));
  INVX1 g9562(.A (lamps[13]), .Y (n_64));
  INVX3 fopt9564(.A (rst), .Y (n_755));
  XNOR2X1 g9566(.A (counter[15]), .B (inc_add_39_26_n_295), .Y
       (n_1121));
  NAND2X2 g9057__9568(.A (lamps[0]), .B (n_914), .Y (n_59));
  NAND2X2 g9059__9570(.A (lamps[1]), .B (n_914), .Y (n_57));
  NAND2X2 g9063__9572(.A (lamps[4]), .B (n_914), .Y (n_56));
  NAND2X2 g8969__9574(.A (lamps[9]), .B (n_914), .Y (n_60));
  NAND2X2 g9065__9576(.A (lamps[10]), .B (n_914), .Y (n_55));
  NAND2X2 g8961__9578(.A (lamps[13]), .B (n_914), .Y (n_61));
  XNOR2X1 g9580(.A (counter[31]), .B (inc_add_39_26_n_299), .Y
       (n_1124));
  INVX3 g9582(.A (n_833), .Y (n_834));
  INVX1 g9584(.A (n_283), .Y (n_37));
  BUFX6 fopt9586(.A (n_815), .Y (n_3));
  XNOR2X1 g9588(.A (counter[19]), .B (inc_add_39_26_n_289), .Y
       (n_1122));
  XNOR2X1 g9590(.A (counter[23]), .B (inc_add_39_26_n_286), .Y
       (n_1123));
  NOR2X1 g9592(.A (n_506), .B (n_514), .Y (n_521));
  INVX1 fopt9596(.A (n_761), .Y (n_760));
  NAND2X2 g9603(.A (n_721), .B (n_1142), .Y (n_1143));
  OAI2BB1X4 g9604(.A0N (n_836), .A1N (n_837), .B0 (n_417), .Y (n_1142));
  NAND2X8 g9605(.A (n_1144), .B (flick), .Y (n_1145));
  CLKAND2X2 g9606(.A (n_827), .B (n_1135), .Y (n_1144));
  NAND3BX4 g2(.AN (n_914), .B (n_180), .C (n_1206), .Y (n_1207));
  AOI21X4 g9664(.A0 (lamps[1]), .A1 (n_860), .B0 (n_824), .Y (n_1206));
  AND2X1 inc_add_39_26_g555__9668(.A (counter[2]), .B (n_425), .Y
       (n_952));
endmodule

